name: ULTRA CI

on: [push, pull request]

jobs:
  test:
    runs-on: ubuntu-18.04
    container: huaweinoah/smarts:v0.4.3-pre
    strategy:
      matrix:
        tests:
          - ./ultra/tests/ --ignore=./ultra/tests/test_train.py
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup X11
        run: |
          /usr/bin/Xorg \
            -noreset \
            +extension GLX \
            +extension RANDR \
            +extension RENDER \
            -logfile ./xdummy.log \
            -config /etc/X11/xorg.conf :1 &
        run: |
          python3.7 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -e .
      - name: Run ultra tests
        run: |
          . .venv/bin/activate
          make build-all-scenarios
          PYTHONHASHSEED=42 pytest -v \
            --doctest-modules \
            --forked \
            --dist=no \
            -n auto \
            ${{matrix.tests}}

