name: ULTRA CI Base Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    container: huaweinoah/smarts:v0.4.3-pre
    strategy:
      matrix:
        tests:
          - ./ultra/tests/ 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup X11
        run: |
          /usr/bin/Xorg \
            -noreset \
            +extension GLX \
            +extension RANDR \
            +extension RENDER \
            -logfile ./xdummy.log \
            -config /etc/X11/xorg.conf :1 &
      - name: Install dependencies
        run: |
          python3.7 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade --upgrade-strategy eager pip
          pip install --upgrade --upgrade-strategy eager wheel
          pip install --upgrade --upgrade-strategy eager -r requirements.txt
          pip install --upgrade --upgrade-strategy eager -e .[train,test]
      - name: Run ultra tests
        run: |
          . .venv/bin/activate
          scl scenario build-all ultra/scenarios/pool
          "python ultra/scenarios/interface.py generate --task 00 --level eval_test --root-dir ultra/tests/scenarios --save-dir ultra/tests/task/eval_test/eval"
          python ultra/train.py --task 00 --level eval_test --policy sac --headless True --episodes 8 --eval-rate 350 --eval-episodes 1 --log-dir ultra/tests/sac_test_models
          pytest -v ./ultra/tests/ 
